export const centers = [
  {
    city_en: 'Kyiv',
    city_ua: 'Київ',
    lat: '50.4500',
    lng: '30.5233',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Kyiv, Misto',
    capital: 'primary',
    population: '2963199',
    population_proper: '2962180',
  },
  {
    city_en: 'Kharkiv',
    city_ua: 'Харків',
    lat: '49.9925',
    lng: '36.2311',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Kharkivska Oblast',
    capital: 'admin',
    population: '1446107',
    population_proper: '1433886',
  },
  {
    city_en: 'Odesa',
    city_ua: 'Одеса',
    lat: '46.4775',
    lng: '30.7326',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Odeska Oblast',
    capital: 'admin',
    population: '1017699',
    population_proper: '1015826',
  },
  {
    city_en: 'Dnipro',
    city_ua: 'Дніпро',
    lat: '48.4675',
    lng: '35.0400',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Dnipropetrovska Oblast',
    capital: 'admin',
    population: '980948',
    population_proper: '980948',
  },
  {
    city_en: 'Donetsk',
    city_ua: 'Донецьк',
    lat: '48.0028',
    lng: '37.8053',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Donetska Oblast',
    capital: 'admin',
    population: '929063',
    population_proper: '929063',
  },
  {
    city_en: 'Zaporizhzhia',
    city_ua: 'Запоріжжя',
    lat: '47.8500',
    lng: '35.1175',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Zaporizka Oblast',
    capital: 'admin',
    population: '741717',
    population_proper: '710052',
  },
  {
    city_en: 'Lviv',
    city_ua: 'Львів',
    lat: '49.8425',
    lng: '24.0322',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Lvivska Oblast',
    capital: 'admin',
    population: '724314',
    population_proper: '724314',
  },
  {
    city_en: 'Sevastopol',
    city_ua: 'Севастополь',
    lat: '44.6050',
    lng: '33.5225',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Sevastopol, Misto',
    capital: 'admin',
    population: '522057',
    population_proper: '522057',
  },
  {
    city_en: 'Mykolaiv',
    city_ua: 'Миколаїв',
    lat: '46.9750',
    lng: '31.9950',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Mykolaivska Oblast',
    capital: 'admin',
    population: '498748',
    population_proper: '470011',
  },
  {
    city_en: 'Luhansk',
    city_ua: 'Луганськ',
    lat: '48.5667',
    lng: '39.3333',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Luhanska Oblast',
    capital: 'admin',
    population: '417990',
    population_proper: '417990',
  },
  {
    city_en: 'Vinnytsia',
    city_ua: 'Вінниця',
    lat: '49.2333',
    lng: '28.4833',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Vinnytska Oblast',
    capital: 'admin',
    population: '371855',
    population_proper: '370601',
  },
  {
    city_en: 'Simferopol',
    city_ua: 'Сімферополь',
    lat: '44.9484',
    lng: '34.1000',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Krym, Avtonomna Respublika',
    capital: 'admin',
    population: '341799',
    population_proper: '340540',
  },
  {
    city_en: 'Poltava',
    city_ua: 'Полтава',
    lat: '49.5894',
    lng: '34.5514',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Poltavska Oblast',
    capital: 'admin',
    population: '317847',
    population_proper: '283402',
  },
  {
    city_en: 'Chernihiv',
    city_ua: 'Чернігів',
    lat: '51.4939',
    lng: '31.2947',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Chernihivska Oblast',
    capital: 'admin',
    population: '294522',
    population_proper: '286899',
  },
  {
    city_en: 'Kherson',
    city_ua: 'Херсон',
    lat: '46.6425',
    lng: '32.6250',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Khersonska Oblast',
    capital: 'admin',
    population: '291428',
    population_proper: '283649',
  },
  {
    city_en: 'Cherkasy',
    city_ua: 'Черкаси',
    lat: '49.4444',
    lng: '32.0597',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Cherkaska Oblast',
    capital: 'admin',
    population: '276360',
    population_proper: '269836',
  },
  {
    city_en: 'Khmelnytskyi',
    city_ua: 'Хмельницький',
    lat: '49.4167',
    lng: '27.0000',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Khmelnytska Oblast',
    capital: 'admin',
    population: '274176',
    population_proper: '274176',
  },
  {
    city_en: 'Chernivtsi',
    city_ua: 'Чернівці',
    lat: '48.3000',
    lng: '25.9333',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Chernivetska Oblast',
    capital: 'admin',
    population: '266550',
    population_proper: '265471',
  },
  {
    city_en: 'Sumy',
    city_ua: 'Суми',
    lat: '50.9167',
    lng: '34.7500',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Sumska Oblast',
    capital: 'admin',
    population: '265758',
    population_proper: '265758',
  },
  {
    city_en: 'Zhytomyr',
    city_ua: 'Житомир',
    lat: '50.2500',
    lng: '28.6667',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Zhytomyrska Oblast',
    capital: 'admin',
    population: '264452',
    population_proper: '263507',
  },
  {
    city_en: 'Rivne',
    city_ua: 'Рівне',
    lat: '50.6192',
    lng: '26.2519',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Rivnenska Oblast',
    capital: 'admin',
    population: '246574',
    population_proper: '245289',
  },
  {
    city_en: 'Ivano-Frankivsk',
    city_ua: 'Івано-Франківськ',
    lat: '48.9228',
    lng: '24.7106',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Ivano-Frankivska Oblast',
    capital: 'admin',
    population: '238196',
    population_proper: '238196',
  },
  {
    city_en: 'Kropyvnytskyi',
    city_ua: 'Кропивницький',
    lat: '48.5000',
    lng: '32.2667',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Kirovohradska Oblast',
    capital: 'admin',
    population: '227413',
    population_proper: '227413',
  },
  {
    city_en: 'Ternopil',
    city_ua: 'Тернопіль',
    lat: '49.5667',
    lng: '25.6000',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Ternopilska Oblast',
    capital: 'admin',
    population: '225238',
    population_proper: '225238',
  },
  {
    city_en: 'Lutsk',
    city_ua: 'Луцьк',
    lat: '50.7500',
    lng: '25.3358',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Volynska Oblast',
    capital: 'admin',
    population: '217197',
    population_proper: '217197',
  },
  {
    city_en: 'Uzhhorod',
    city_ua: 'Ужгород',
    lat: '48.6239',
    lng: '22.2950',
    country: 'Ukraine',
    iso2: 'UA',
    admin_name: 'Zakarpatska Oblast',
    capital: 'admin',
    population: '114897',
    population_proper: '114897',
  },
];
